/** @type {import('tailwindcss').Config} */

/**
 * rlayAi — "The Blues" brand palette.
 *
 * Four brand colours, plus white and black. Nothing else.
 * The numbered steps are tints and shades of those same four hues, used for
 * borders, hovers and muted text.
 *
 * The five brand colours come from brand_colors.png; the 50–950 ramps are
 * generated by mixing each toward white (lighter) and black (darker), so every
 * step stays on-hue.
 *
 * Contrast, measured (WCAG AA needs 4.5 for body text, 3.0 for large):
 *   white on Orion .......... 4.69  ok for buttons and body
 *   white on Indigo ......... 8.31
 *   white on Midnight ...... 16.63
 *   Euphoria on Midnight .... 8.05
 *   Euphoria on white ....... 2.06  NEVER use for text on light grounds -
 *                                   it is a fill, border and dark-ground accent
 */
const brand = {
  orion: '#4563FF',    // primary
  euphoria: '#A1B0FF', // highlight
  indigo: '#3345A4',   // depth
  midnight: '#0E1752', // typography / dark ground
};

export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        brand,

        // Orion Blue — primary actions, links, active states
        primary: {
          DEFAULT: brand.orion,
          50: '#F6F7FF', 100: '#E9ECFF', 200: '#CFD6FF', 300: '#B1BDFF',
          400: '#8195FF', 500: '#4563FF', 600: '#3B55DB', 700: '#3045B2',
          800: '#25358A', 900: '#1A2661', 950: '#11183D',
        },

        // Euphoria Blue — badges, borders, dark-ground text
        secondary: {
          DEFAULT: brand.euphoria,
          50: '#FAFBFF', 100: '#F4F6FF', 200: '#E7EAFF', 300: '#D8DEFF',
          400: '#BFC9FF', 500: '#A1B0FF', 600: '#8A97DB', 700: '#717BB2',
          800: '#575F8A', 900: '#3D4361', 950: '#272A3D',
        },

        // Indigo — subheadings, icons, department active states.
        // Named "ink" so it does not shadow Tailwind's built-in indigo.
        ink: {
          DEFAULT: brand.indigo,
          50: '#F5F6FA', 100: '#E7E9F4', 200: '#CACFE7', 300: '#A9B1D9',
          400: '#7481C1', 500: '#3345A4', 600: '#2C3B8D', 700: '#243073',
          800: '#1C2559', 900: '#131A3E', 950: '#0C1127',
        },

        // Midnight Navy — headings and dark sections
        dark: {
          DEFAULT: brand.midnight,
          50: '#F3F3F6', 100: '#E2E3EA', 200: '#C0C3D2', 300: '#9A9EB6',
          400: '#5B6189', 500: '#0E1752', 600: '#0C1447', 700: '#0A1039',
          800: '#080C2C', 900: '#05091F', 950: '#030614',
        },

      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'Segoe UI', 'Roboto', 'sans-serif'],
        display: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
      },
      letterSpacing: {
        tighter: '-0.03em',
      },
      boxShadow: {
        'soft': '0 2px 15px -3px rgba(14, 23, 82, 0.08), 0 10px 20px -2px rgba(14, 23, 82, 0.04)',
        'lift': '0 20px 40px -12px rgba(14, 23, 82, 0.18)',
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'slide-down': 'slideDown 0.3s ease-out',
        'scale-in': 'scaleIn 0.2s ease-out',
        'float': 'float 6s ease-in-out infinite',
        'marquee': 'marquee 30s linear infinite',
      },
      keyframes: {
        fadeIn: { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.9)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-14px)' },
        },
        marquee: {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
      },
    },
  },
  plugins: [],
}
