// Permission definitions matching backend
export enum Permission {
  // Dashboard permissions
  VIEW_DASHBOARD = 'VIEW_DASHBOARD',

  // Conversation permissions
  VIEW_ALL_CONVERSATIONS = 'VIEW_ALL_CONVERSATIONS',
  VIEW_ASSIGNED_CONVERSATIONS = 'VIEW_ASSIGNED_CONVERSATIONS',
  ASSIGN_CONVERSATIONS = 'ASSIGN_CONVERSATIONS',
  CLOSE_CONVERSATIONS = 'CLOSE_CONVERSATIONS',
  EXPORT_CONVERSATIONS = 'EXPORT_CONVERSATIONS',

  // Staff permissions
  VIEW_STAFF = 'VIEW_STAFF',
  CREATE_STAFF = 'CREATE_STAFF',
  UPDATE_STAFF = 'UPDATE_STAFF',
  DELETE_STAFF = 'DELETE_STAFF',
  MANAGE_STAFF_ROLES = 'MANAGE_STAFF_ROLES',

  // Department permissions
  VIEW_DEPARTMENTS = 'VIEW_DEPARTMENTS',
  CREATE_DEPARTMENTS = 'CREATE_DEPARTMENTS',
  UPDATE_DEPARTMENTS = 'UPDATE_DEPARTMENTS',
  DELETE_DEPARTMENTS = 'DELETE_DEPARTMENTS',

  // Knowledge Base permissions
  VIEW_KNOWLEDGE_BASE = 'VIEW_KNOWLEDGE_BASE',
  CREATE_KNOWLEDGE_ARTICLES = 'CREATE_KNOWLEDGE_ARTICLES',
  UPDATE_KNOWLEDGE_ARTICLES = 'UPDATE_KNOWLEDGE_ARTICLES',
  DELETE_KNOWLEDGE_ARTICLES = 'DELETE_KNOWLEDGE_ARTICLES',

  // FAQ permissions
  VIEW_FAQS = 'VIEW_FAQS',
  CREATE_FAQS = 'CREATE_FAQS',
  UPDATE_FAQS = 'UPDATE_FAQS',
  DELETE_FAQS = 'DELETE_FAQS',

  // Analytics permissions
  VIEW_ANALYTICS = 'VIEW_ANALYTICS',
  VIEW_ADVANCED_ANALYTICS = 'VIEW_ADVANCED_ANALYTICS',
  EXPORT_ANALYTICS = 'EXPORT_ANALYTICS',

  // Settings permissions
  VIEW_COMPANY_SETTINGS = 'VIEW_COMPANY_SETTINGS',
  UPDATE_COMPANY_SETTINGS = 'UPDATE_COMPANY_SETTINGS',
  VIEW_WIDGET_SETTINGS = 'VIEW_WIDGET_SETTINGS',
  UPDATE_WIDGET_SETTINGS = 'UPDATE_WIDGET_SETTINGS',

  // Platform Admin permissions (SUPER_ADMIN, ADMIN only)
  VIEW_ALL_COMPANIES = 'VIEW_ALL_COMPANIES',
  CREATE_COMPANIES = 'CREATE_COMPANIES',
  UPDATE_COMPANIES = 'UPDATE_COMPANIES',
  DELETE_COMPANIES = 'DELETE_COMPANIES',
  VIEW_PLATFORM_ANALYTICS = 'VIEW_PLATFORM_ANALYTICS',
  MANAGE_PLATFORM_SETTINGS = 'MANAGE_PLATFORM_SETTINGS',
}
